# Travis CI configuration file.

sudo: required

language: node_js

node_js:
  - '11'
  - '10'

addons:
  chrome: stable

stages:
  - compile
  - test

jobs:
  include:

    - stage: compile
      script:
        - npx npm-install-peers
        - npm run build
        - npm run build:demo
        - npm run build:gh-pages

    - stage: test
      script:
        - npm run lint
        - npm run test
        # - npm run e2e

    - stage: deploy
      script: skip # usually you do not want to rerun any tests
      deploy: &heroku
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/gh-pages
        on:
          branch: master
