# Travis CI configuration file.

sudo: required

language: node_js

node_js:
  - '11'
  - '10'

addons:
  chrome: stable

stages:
  - compile
  - name: compile-gh-pages
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
  - test

jobs:
  include:

    - stage: compile
      script:
        - npx npm-install-peers
        - npm run build
        - npm run build:demo

    - stage: compile-gh-pages
      script:
        - npm run build:gh-pages

    - stage: test
      script:
        - npm run lint
        - npm run test
        # - npm run e2e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/gh-pages
  on:
    branch: master
