# Travis CI configuration file.

sudo: required

language: node_js
node_js: stable

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  addons:
    chrome: stable
  include:

    - stage: compile
      script:
        - npx npm-install-peers
        - yarn build

    - stage: test
      script:
        - yarn lint
        - yarn test
        # - yarn e2e

    - stage: deploy
      script:
        - yarn deploy:demo
