# Travis CI configuration file.

sudo: required

language: node_js

node_js:
  - '11'
  - '10'

addons:
  chrome: stable

stages:
  - compile
  - test
  - deploy-demo

jobs:
  include:

    - stage: compile
      script:
        - npx npm-install-peers
        - npm run build

    - stage: test
      script:
        - npm run lint
        - npm run test
        # - npm run e2e

    - stage: deploy-demo
      if: branch = master
      script:
        - npm i
        - npm run deploy:demo
