# Travis CI configuration file.

sudo: required

language: node_js
node_js: stable

addons:
  chrome: stable

stages:
  - compile
  - test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:

    - stage: compile
      script:
        - npx npm-install-peers
        - npm run build

    - stage: test
      script:
        - npm run lint
        - npm run test
        # - npm run e2e

    - stage: deploy
      if: branch = master
      script:
        - npm run deploy:demo
