# Travis CI configuration file.

sudo: required

language: node_js

node_js:
  - '11'
  - '10'

addons:
  chrome: stable

stages:
  - compile
  - test

jobs:
  include:

    - stage: compile
      script:
        - npx npm-install-peers
        - npm run build
        - npm run build:demo

    - stage: test
      script:
        - npm run lint
        - npm run test
        # - npm run e2e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/zxing-scanner-demo
  on:
    branch: master
